import { ChatInputCommandInteraction, EmbedBuilder, SlashCommandBuilder } from 'discord.js'
import { questions } from '../../data/questions.js'

export const command = {
	data: new SlashCommandBuilder()
		.setName('question')
		.setDescription('Generate a random conversation starter question')
	,
	async execute(interaction: ChatInputCommandInteraction) {
		const randomIndex = Math.floor(Math.random() * questions.length)
		const question = questions[randomIndex]
		
		const questionEmbed = new EmbedBuilder()
			.setTitle('Your Random Question')
			.setDescription(question)
			.setColor('Blue')
			.setFooter({
				iconURL: 'https://conversationstartersworld.com/wp-content/uploads/2015/10/cropped-CSW-favicon-1.png',
				text: 'Generated by conversationstartersworld.com'
			})
		
		interaction.reply({ embeds: [questionEmbed] })
	}

}